---
####################
####################
## Auto Formatter ##
####################
####################
name: Formate Code

#
# Documentation:
# https://github.com/mezgoodle/auto-formatter
#

#############################
# Start the job on all push #
#############################
on: push

###############
# Set the Job #
###############
jobs:
  build:
    # Name the Job
    name: Format Code
    # Set the agent to run on
    runs-on: ubuntu-latest

    ##################
    # Load all steps #
    ##################
    steps:
      ##########################
      # Checkout the code base #
      ##########################
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          # Full git history is needed to get a proper list of changed files within `auto-formatter`
          fetch-depth: 0

      - name: Mark github workspace as safe
        run: |
          git config --global --add safe.directory /github/workspace

      ################################
      # Run Auto-formatter against code base #
      ################################
      - name: Auto-Formatter
        uses: mezgoodle/auto-formatter@v1.0.2
